language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm test
  - npm run selenium:browserstack
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
